import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Class 8 Stylized Pages</h1>
        <div className={styles.container}>
          <Link href="/useEffectOne" className={styles.pageLink}>useEffectOne</Link>
          <Link href="/useEffectTwo" className={styles.pageLink}>useEffectTwo</Link>
          <Link href="/useEffectThree" className={styles.pageLink}>useEffectThree</Link>
          <Link href="/carouselPage" className={styles.pageLink}>carouselPage</Link>
        </div>
      </main>
    </>
  )
}
